#!/usr/bin/python3
import sys
import re
import requests
import time
from steamlinuxchecker import *


def get_page(url):
    r = requests.get(url)
    assert r.status_code == 200, "Can't open %s (%d)" % (url, r.status_code)
    return r.text

def get_steam_group_members(xml):
    rx = re.compile(r'steamID64>(\d+)')
    ids = []
    for match in rx.finditer(xml):
        ids.append(match.group(1))
    return sorted(ids)

def main():
    usage = """
    Usage:
        {} group_name|guid

        group_name
            Part of the group URL after `/groups/`.

        guid
            Steam internal value `groupID64`.
    """.format(sys.argv[0])

    if len(sys.argv) == 1:
        raise SystemExit(usage)

    xml = get_page('http://steamcommunity.com/groups/%s/memberslistxml/?xml=1' % sys.argv[1])

    steamapi = get_steam_api()

    for id in get_steam_group_members(xml):
        user = get_steam_user(steamapi, id)
        print_user_summary(user, check_steam_user(user, False))
        time.sleep(2)


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit("\nExiting...\n");
