#!/usr/bin/python3.5
import sys
from steamlinuxchecker import *


def main():
    usage = """
    Usage:
        {} vanity_name|steam_id

        vanity_name
            Part of the user URL after `/id/`.

        steam_id
            Number in the user URL after `/profiles/`.
    """.format(sys.argv[0])

    if len(sys.argv) == 1:
        raise SystemExit(usage)

    user = get_steam_user(get_steam_api(), sys.argv[1])
    check_steam_user(user, True)


if __name__ == '__main__':
    main()
