#!/usr/bin/python3.5
import configparser
import sys
from steamapi import steamapi
from steamhtml import Scraper

usage = """
Usage:
    {} vanity_name|steam_id

    vanity_name
        Part of the URL after `/id/`.

    steam_id
        Number in the URL after `/profiles/`.
""".format(sys.argv[0])

if len(sys.argv) == 1:
    raise SystemExit(usage)

config = configparser.ConfigParser()
config.read('config.ini')

try:
    steamapi.core.APIConnection(api_key=config['api']['key'])
except KeyError:
    raise SystemExit('Copy config_example.ini to config.ini and set the api.key value!')

target = sys.argv[1]

try:
  user = steamapi.user.SteamUser(userid=int(target))
except ValueError:
  user = steamapi.user.SteamUser(userurl=target)

total = 0
linux = 0
scraper = Scraper()
for game in user.games:
    total += game.playtime_forever
    badge = '-----'
    if scraper.runs_on_linux(game.id):
        badge = 'LINUX'
        linux += game.playtime_forever
    print(badge, '%6s' % game.playtime_forever, game.name)

summary = "\nTotal playtime: {}\nLinux playtime: {}\nPlaytime score: {:0%}"
print(summary.format(total, linux, linux/total))
