#!/usr/bin/python3
import configparser
import steamapi.steamapi as steamapi
from steamhtml import Scraper

config = configparser.ConfigParser()
config.read('config.ini')

try:
    steamapi.core.APIConnection(api_key=config['api']['key'])
except KeyError:
    raise SystemExit('Copy config_example.ini to config.ini and set the api.key value!')

user = steamapi.user.SteamUser(userurl="cprn")

total = 0
linux = 0
scraper = Scraper()
for game in user.games:
    total += game.playtime_forever
    badge = '-----'
    if scraper.runs_on_linux(game.id):
        badge = 'LINUX'
        linux += game.playtime_forever
    print(badge, '%6s' % game.playtime_forever, game.name)

summary = "\nTotal playtime: {}\nLinux playtime: {}\nPlaytime score: {:0%}"
print(summary.format(total, linux, linux/total))
